name: openapi_spec
description: OpenAPI Specification generator using native Dart code, as well as an all-in-one parser of existing specifications.
version: 0.7.19
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/openapi_spec
issue_tracker: https://github.com/tazatechnology/openapi_spec/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/openapi_spec

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  yaml: ^3.1.2
  path: ">=1.8.0 <2.0.0"
  
  # For generated client code
  intl: ">=0.17.0 <1.0.0"
  http: ">=0.13.0 <2.0.0"
  recase: ^4.1.0

  # For CLI
  args: ^2.5.0
  mason_logger: ^0.2.16
  pub_updater: ^0.4.0
  cli_completion: ^0.5.0
  
dev_dependencies:
  build_runner: ^2.4.11
  lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.8
  build_verify: ^3.1.0
  build_version: ^2.1.1

executables:
  openapi_spec: